title: Research Handbook
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sriharshapy.github.io/research-handbook

aux_links:
  Template Repository: https://sriharshapy.github.io/research-handbook

remote_theme: pmarsceill/just-the-docs

# Navigation configuration
just_the_docs:
  search_enabled: true

  nav:
    - title: "Home"
      url: /
    - title: "Deep Decoder"
      url: /deep-decoder/
      children:
        - title: "Model"
          url: /deep-decoder/model/
